reload:
  name: Reload
  description: Reload PV Excess Manager configuration

reset_device_on_time:
  name: Reset devices ON-time
  description: Reset the ON-time for all devices to zero.
  target:
    entity:
      integration: pv_excess_manager
